# Generated by Django 6.1 on 2026-09-09 19:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'acteur")),
                ('type_acteur', models.CharField(choices=[('gouvernement', 'Gouvernement'), ('entreprise_publique', 'Entreprise publique'), ('entreprise_privee', 'Entreprise privée'), ('institution_financiere', 'Institution financière'), ('ong', 'ONG'), ('organisation_internationale', 'Organisation internationale'), ('personnalite_politique', 'Personnalité politique'), ('universite', 'Université / Centre de recherche')], max_length=50, verbose_name="Type d'acteur")),
                ('categorie', models.CharField(choices=[('personne_morale', 'Personne morale'), ('personne_physique', 'Personne physique')], default='personne_morale', max_length=50, verbose_name='Catégorie')),
                ('pays', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('site_web', models.URLField(blank=True, max_length=255, null=True, verbose_name='Site web')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('date_disparition', models.DateField(blank=True, null=True, verbose_name='Date de disparition')),
            ],
            options={
                'verbose_name': 'Acteur',
                'verbose_name_plural': 'Acteurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Chronologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_lancement_travaux', models.DateField(blank=True, null=True, verbose_name='Date de lancement des travaux')),
                ('date_mise_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service commerciale (COD)')),
                ('duree_vie', models.CharField(blank=True, max_length=50, null=True, verbose_name='Durée de vie')),
                ('type_entree', models.CharField(choices=[('etape', 'Étape'), ('evenement', 'Événement'), ('impact', 'Impact'), ('decision', 'Décision')], max_length=50, verbose_name="Type d'entrée")),
            ],
            options={
                'verbose_name': 'Chronologie',
                'verbose_name_plural': 'Chronologies',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EtapeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name="Nom de l'étape")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('achevee', 'Achevée'), ('en_cours', 'En cours'), ('reportee', 'Reportée'), ('annulee', 'Annulée')], default='en_cours', max_length=50, verbose_name='Statut')),
                ('objectifs', models.TextField(blank=True, null=True, verbose_name='Objectifs')),
                ('resultats', models.TextField(blank=True, null=True, verbose_name='Résultats')),
                ('responsable_etape', models.CharField(blank=True, max_length=200, null=True, verbose_name="Responsable de l'étape")),
            ],
            options={
                'verbose_name': 'Étape du projet',
                'verbose_name_plural': 'Étapes du projet',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du projet')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('capacite_prevue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Capacité prévue (MW)')),
                ('investissement_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Investissement estimé (USD)')),
                ('statut_actuel', models.CharField(choices=[('etude', 'En étude'), ('planification', 'En planification'), ('suspendu', 'Suspendu'), ('en_cours', 'En cours'), ('acheve', 'Achevé')], default='en_cours', max_length=50, verbose_name='Statut actuel')),
                ('date_debut_projet', models.DateField(blank=True, null=True, verbose_name='Date de début du projet')),
                ('date_fin_prevue', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('coordonnees_gps', models.CharField(blank=True, max_length=50, null=True, verbose_name='Coordonnées GPS')),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200, null=True, verbose_name="Maître d'ouvrage")),
                ('hauteur_chute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hauteur de chute (m)')),
                ('nombre_turbines', models.IntegerField(blank=True, null=True, verbose_name='Nombre de turbines')),
                ('type_turbines', models.CharField(blank=True, choices=[('francis', 'Francis'), ('kaplan', 'Kaplan'), ('pelton', 'Pelton'), ('autre', 'Autre')], max_length=100, null=True, verbose_name='Type de turbines')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('chercheur', 'Chercheur / Analyste'), ('decideur', 'Décideur'), ('public', 'Public / Visiteur')], default='public', max_length=20, verbose_name='Rôle')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date de création')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActeurEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('initiateur', 'Initiateur'), ('participant', 'Participant'), ('opposant', 'Opposant'), ('beneficiaire', 'Bénéficiaire'), ('observateur', 'Observateur'), ('victime', 'Victime')], max_length=100, null=True, verbose_name="Rôle dans l'événement")),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.acteur', verbose_name='Acteur')),
            ],
            options={
                'verbose_name': 'Liaison acteur-événement',
                'verbose_name_plural': 'Liaisons acteurs-événements',
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_evenement', models.DateField(verbose_name="Date de l'événement")),
                ('type_evenement', models.CharField(choices=[('politique', 'Politique'), ('financier', 'Financier'), ('technique', 'Technique'), ('diplomatique', 'Diplomatique'), ('social', 'Social'), ('environnemental', 'Environnemental'), ('juridique', 'Juridique')], max_length=50, verbose_name="Type d'événement")),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Importance (1-5)')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name="Source de l'information")),
                ('localisation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localisation')),
                ('acteurs', models.ManyToManyField(related_name='evenements', through='core.ActeurEvenement', to='core.acteur', verbose_name='Acteurs impliqués')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.AddField(
            model_name='acteurevenement',
            name='evenement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evenement', verbose_name='Événement'),
        ),
        migrations.CreateModel(
            name='ImpactActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impact', models.CharField(choices=[('positif', 'Positif'), ('negatif', 'Négatif'), ('neutre', 'Neutre'), ('decisif', 'Décisif'), ('bloquant', 'Bloquant'), ('facilitateur', 'Facilitateur')], max_length=50, verbose_name="Type d'impact")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_impact', models.DateField(blank=True, null=True, verbose_name="Date de l'impact")),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Importance (1-5)')),
                ('consequences', models.TextField(blank=True, null=True, verbose_name='Conséquences')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='core.acteur', verbose_name='Acteur')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacts_acteurs', to='core.etapeprojet', verbose_name='Étape concernée')),
            ],
            options={
                'verbose_name': "Impact d'acteur",
                'verbose_name_plural': 'Impacts des acteurs',
                'ordering': ['-importance', 'date_impact'],
            },
        ),
        migrations.CreateModel(
            name='ImpactEnvironnementalSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_impact', models.CharField(choices=[('environnemental', 'Environnemental'), ('social', 'Social'), ('economique', 'Économique')], max_length=50, verbose_name="Type d'impact")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_impact', models.DateField(blank=True, null=True, verbose_name="Date de l'impact")),
                ('surface_ennoyee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Surface ennoyée (km²)')),
                ('volume_reservoir', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Volume du réservoir (millions m³)')),
                ('population_deplacee', models.IntegerField(blank=True, null=True, verbose_name='Population déplacée (personnes)')),
                ('bilan_carbone', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Bilan carbone (t CO₂)')),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Importance (1-5)')),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impacts_es', to='core.etapeprojet', verbose_name='Étape concernée')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts_environnementaux', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Impact environnemental et social',
                'verbose_name_plural': 'Impacts environnementaux et sociaux',
                'ordering': ['-importance', 'date_impact'],
            },
        ),
        migrations.AddField(
            model_name='etapeprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='core.projet', verbose_name='Projet'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du document')),
                ('type_document', models.CharField(choices=[('rapport', 'Rapport'), ('etude', 'Étude'), ('archive', 'Archive'), ('correspondance', 'Correspondance'), ('contrat', 'Contrat'), ('article', 'Article'), ('these', 'Thèse / Mémoire'), ('communique', 'Communiqué de presse')], max_length=50, verbose_name='Type de document')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('auteur', models.CharField(blank=True, max_length=200, null=True, verbose_name='Auteur')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Résumé')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Fichier')),
                ('mots_cles', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mots-clés')),
                ('etat_conservation', models.CharField(choices=[('bon', 'Bon'), ('moyen', 'Moyen'), ('mauvais', 'Mauvais'), ('inconnu', 'Inconnu')], default='inconnu', max_length=50, verbose_name='État de conservation')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.projet', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='acteurevenement',
            unique_together={('acteur', 'evenement')},
        ),
    ]
